import java.util.Random;
import java.util.Scanner;
public class Main
{
	public static void main(String[] args) {
	    int score=0;
	    int maxattempt=3;
	    Random r=new Random();
	    int num1=r.nextInt(100);
	    Scanner sc=new Scanner(System.in);
	    for(int i=0;i<maxattempt;i++){
	    System.out.println("Enter a number: ");
	    int num2=sc.nextInt();
	    System.out.println("The number generated by system: " +num1);
	    System.out.println("The number entered by the user: " +num2);
	    
	    if(num1==num2){
	        System.out.println("The user score is "+score++);
	    }
	    else if(num1<num2){
	        System.out.println("The number is low.");
	    }
	    else{
	        System.out.println("The number is higher.");
	    }
	    
	}
}
}